### ISSUE TITLE
Hyperparameters for each environment-agent combination

### ISSUE THREAD

**Issue by hercky** [openai/safety-starter-agents#2]
Hello 

In the paper, you mention that the results are presented with the hand-tuned hyperparameters for each algorithm class (Sec 5.2). Can you also share those hyperparams?  This will save the computation cost for the grid search as well as add to the reproducibility value.

**Comment by jachiam** [comment]
The default hyperparameters in the codebase for each algorithm are the hand-tuned hyperparameters in the paper. :)
